import Link from 'next/link';

const customers = [
  { name: 'Ama Mensah', phone: '024 123 4567', type: 'VIP', orders: 8, spent: 'GH₵ 2,840', outstanding: 'GH₵ 0' },
  { name: 'Esi Boateng', phone: '055 234 5678', type: 'Returning', orders: 4, spent: 'GH₵ 1,420', outstanding: 'GH₵ 220' },
  { name: 'Adwoa Owusu', phone: '020 345 6789', type: 'New', orders: 1, spent: 'GH₵ 180', outstanding: 'GH₵ 180' },
];

export default function CustomersPage() { return <main className="min-h-screen"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><div><p className="text-sm font-extrabold tracking-wide text-indigo-600">CUSTOMERS</p><h1 className="mt-1 text-2xl font-bold">Customer Management</h1></div><Link href="/customers/new" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white">+ Add Customer</Link></div></header><div className="mx-auto max-w-7xl px-5 py-7 lg:px-8"><div className="mb-5 rounded-2xl border bg-white p-4"><input className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-indigo-400" placeholder="Search by customer name or phone..." /></div><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-slate-50 text-slate-500"><tr>{['Customer','Phone','Type','Orders','Total spent','Outstanding'].map(h=><th key={h} className="px-5 py-4 font-semibold">{h}</th>)}</tr></thead><tbody>{customers.map(c=><tr key={c.phone} className="border-b last:border-0 hover:bg-slate-50"><td className="px-5 py-4 font-semibold">{c.name}</td><td className="px-5 py-4 text-slate-600">{c.phone}</td><td className="px-5 py-4"><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">{c.type}</span></td><td className="px-5 py-4">{c.orders}</td><td className="px-5 py-4 font-semibold">{c.spent}</td><td className="px-5 py-4 font-semibold">{c.outstanding}</td></tr>)}</tbody></table></div></div></div></main>; }
