import Link from 'next/link';

const orders = [
  { id: '#ORD-001', customer: 'Ama Mensah', item: 'Ankara Dress', total: 'GH₵ 350', paid: 'GH₵ 350', status: 'Delivered', payment: 'Paid' },
  { id: '#ORD-002', customer: 'Esi Boateng', item: 'Two-Piece Set', total: 'GH₵ 420', paid: 'GH₵ 200', status: 'Preparing', payment: 'Partial' },
  { id: '#ORD-003', customer: 'Adwoa Owusu', item: 'Linen Shirt', total: 'GH₵ 180', paid: 'GH₵ 0', status: 'New', payment: 'Unpaid' },
];

export default function OrdersPage() {
  return <main className="min-h-screen"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><div><p className="text-sm font-extrabold tracking-wide text-indigo-600">ORDERS</p><h1 className="mt-1 text-2xl font-bold">Sales & Orders</h1></div><Link href="/orders/new" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white">+ New Order</Link></div></header><div className="mx-auto max-w-7xl px-5 py-7 lg:px-8"><div className="mb-5 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Total orders</p><p className="mt-2 text-2xl font-bold">3</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Payment outstanding</p><p className="mt-2 text-2xl font-bold">GH₵ 400</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Awaiting delivery</p><p className="mt-2 text-2xl font-bold">1</p></div></div><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b bg-slate-50 text-slate-500"><tr>{['Order','Customer','Item','Total','Paid','Payment','Status'].map(h=><th key={h} className="px-5 py-4 font-semibold">{h}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-b last:border-0 hover:bg-slate-50"><td className="px-5 py-4 font-semibold">{o.id}</td><td className="px-5 py-4">{o.customer}</td><td className="px-5 py-4 text-slate-600">{o.item}</td><td className="px-5 py-4 font-semibold">{o.total}</td><td className="px-5 py-4">{o.paid}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{o.payment}</span></td><td className="px-5 py-4"><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">{o.status}</span></td></tr>)}</tbody></table></div></div></div></main>;
}
