import Link from 'next/link';

const expenses = [
  { date: '10 Sep 2026', category: 'Stock', description: 'Ankara fabric restock', amount: 'GH₵ 1,200', method: 'MoMo' },
  { date: '09 Sep 2026', category: 'Delivery', description: 'Customer deliveries', amount: 'GH₵ 120', method: 'Cash' },
  { date: '07 Sep 2026', category: 'Marketing', description: 'Instagram promotion', amount: 'GH₵ 80', method: 'MoMo' },
];

export default function ExpensesPage() { return <main className="min-h-screen"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><div><p className="text-sm font-extrabold tracking-wide text-indigo-600">EXPENSES</p><h1 className="mt-1 text-2xl font-bold">Business Expenses</h1></div><Link href="/expenses/new" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white">+ Add Expense</Link></div></header><div className="mx-auto max-w-7xl px-5 py-7 lg:px-8"><div className="mb-5 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">This month</p><p className="mt-2 text-2xl font-bold">GH₵ 1,400</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Stock</p><p className="mt-2 text-2xl font-bold">GH₵ 1,200</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Other expenses</p><p className="mt-2 text-2xl font-bold">GH₵ 200</p></div></div><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b bg-slate-50 text-slate-500"><tr>{['Date','Category','Description','Amount','Payment method'].map(h=><th key={h} className="px-5 py-4 font-semibold">{h}</th>)}</tr></thead><tbody>{expenses.map(e=><tr key={e.date+e.description} className="border-b last:border-0 hover:bg-slate-50"><td className="px-5 py-4">{e.date}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{e.category}</span></td><td className="px-5 py-4 font-semibold">{e.description}</td><td className="px-5 py-4 font-semibold">{e.amount}</td><td className="px-5 py-4 text-slate-600">{e.method}</td></tr>)}</tbody></table></div></div></div></main>; }
